// ================================================================
// WORDS DATABASE — Imposter Game
// Images stored locally in the "images/" folder
// Filename format: images/word-name.jpg  (all lowercase, spaces = hyphens)
// ================================================================

const WORDS = [

  // ── Animals ──────────────────────────────────────────────────
  { word: "Elephant",       category: "Animals",     image: "images/elephant.jpg" },
  { word: "Tiger",          category: "Animals",     image: "images/tiger.jpg" },
  { word: "Penguin",        category: "Animals",     image: "images/penguin.jpg" },
  { word: "Dolphin",        category: "Animals",     image: "images/dolphin.jpg" },
  { word: "Giraffe",        category: "Animals",     image: "images/giraffe.jpg" },
  { word: "Lion",           category: "Animals",     image: "images/lion.jpg" },
  { word: "Panda",          category: "Animals",     image: "images/panda.jpg" },
  { word: "Shark",          category: "Animals",     image: "images/shark.jpg" },
  { word: "Eagle",          category: "Animals",     image: "images/eagle.jpg" },
  { word: "Gorilla",        category: "Animals",     image: "images/gorilla.jpg" },
  { word: "Flamingo",       category: "Animals",     image: "images/flamingo.jpg" },
  { word: "Cheetah",        category: "Animals",     image: "images/cheetah.jpg" },
  { word: "Polar Bear",     category: "Animals",     image: "images/polar-bear.jpg" },
  { word: "Chameleon",      category: "Animals",     image: "images/chameleon.jpg" },
  { word: "Octopus",        category: "Animals",     image: "images/octopus.jpg" },
  { word: "Kangaroo",       category: "Animals",     image: "images/kangaroo.jpg" },
  { word: "Parrot",         category: "Animals",     image: "images/parrot.jpg" },
  { word: "Wolf",           category: "Animals",     image: "images/wolf.jpg" },
  { word: "Crocodile",      category: "Animals",     image: "images/crocodile.jpg" },
  { word: "Peacock",        category: "Animals",     image: "images/peacock.jpg" },

  // ── Food ─────────────────────────────────────────────────────
  { word: "Pizza",          category: "Food",        image: "images/pizza.jpg" },
  { word: "Porotta",        category: "Food",        image: "images/porotta.jpg" },
  { word: "Burger",         category: "Food",        image: "images/burger.jpg" },
  { word: "Apple",          category: "Food",        image: "images/apple.jpg" },
  { word: "Ice Cream",      category: "Food",        image: "images/ice-cream.jpg" },
  { word: "Mango",          category: "Food",        image: "images/mango.jpg" },
  { word: "Cake",           category: "Food",        image: "images/cake.jpg" },
  { word: "Noodles",        category: "Food",        image: "images/noodles.jpg" },
  { word: "KFC",            category: "Food",        image: "images/kfc.jpg" },
  { word: "Oreo",           category: "Food",        image: "images/oreo.jpg" },
  { word: "Donut",          category: "Food",        image: "images/donut.jpg" },
  { word: "Cupcake",        category: "Food",        image: "images/cupcake.jpg" },
  { word: "Strawberry",     category: "Food",        image: "images/strawberry.jpg" },
  { word: "Watermelon",     category: "Food",        image: "images/watermelon.jpg" },
  { word: "Popcorn",        category: "Food",        image: "images/popcorn.jpg" },
  { word: "Lollipop",       category: "Food",        image: "images/lollipop.jpg" },
  { word: "Nutella",        category: "Food",        image: "images/nutella.jpg" },
  { word: "Cocacola",       category: "Food",        image: "images/cocacola.jpg" },
  { word: "Banana",         category: "Food",        image: "images/banana.jpg" },
  { word: "Chocolate",      category: "Food",        image: "images/chocolate.jpg" },
  { word: "Laddoo",         category: "Food",        image: "images/laddoo.jpg" },
  { word: "Pineapple",      category: "Food",        image: "images/pineapple.jpg" },

  // ── Transport ────────────────────────────────────────────────
  { word: "Auto Rickshaw",  category: "Transport",   image: "images/auto-rickshaw.jpg" },
  { word: "Bicycle",        category: "Transport",   image: "images/bicycle.jpg" },
  { word: "Train",          category: "Transport",   image: "images/train.jpg" },
  { word: "Ambulance",      category: "Transport",   image: "images/ambulance.jpg" },
  { word: "Scooter",        category: "Transport",   image: "images/scooter.jpg" },
  { word: "Jeep",           category: "Transport",   image: "images/jeep.jpg" },
  { word: "Helicopter",     category: "Transport",   image: "images/helicopter.jpg" },
  { word: "Airplane",       category: "Transport",   image: "images/airplane.jpg" },
  { word: "Car",            category: "Transport",   image: "images/car.jpg" },
  { word: "Fire Truck",     category: "Transport",   image: "images/fire-truck.jpg" },
  { word: "Bike",           category: "Transport",   image: "images/bike.jpg" },
  { word: "Boat",           category: "Transport",   image: "images/boat.jpg" },
  { word: "Lorry",          category: "Transport",   image: "images/lorry.jpg" },
  { word: "Rocket",         category: "Transport",   image: "images/rocket.jpg" },

  // ── Nature ───────────────────────────────────────────────────
  { word: "Rainbow",        category: "Nature",      image: "images/rainbow.jpg" },
  { word: "Desert",         category: "Nature",      image: "images/desert.jpg" },
  { word: "Moon",           category: "Nature",      image: "images/moon.jpg" },
  { word: "Earth",          category: "Nature",      image: "images/earth.jpg" },
  { word: "Cactus",         category: "Nature",      image: "images/cactus.jpg" },
  { word: "Rose",           category: "Nature",      image: "images/rose.jpg" },
  { word: "Rain",           category: "Nature",      image: "images/rain.jpg" },
  { word: "Cloud",          category: "Nature",      image: "images/cloud.jpg" },
  { word: "Mushroom",       category: "Nature",      image: "images/mushroom.jpg" },
  { word: "Sea",            category: "Nature",      image: "images/sea.jpg" },
  { word: "Sun",            category: "Nature",      image: "images/sun.jpg" },
  { word: "Tree",           category: "Nature",      image: "images/tree.jpg" },
  { word: "Fire",           category: "Nature",      image: "images/fire.jpg" },
  { word: "Stone",          category: "Nature",      image: "images/stone.jpg" },
  { word: "Thunder",        category: "Nature",      image: "images/thunder.jpg" },

  // ── Sports & Games ───────────────────────────────────────────
  { word: "Cricket",            category: "Sports",  image: "images/cricket.jpg" },
  { word: "Football",           category: "Sports",  image: "images/football.jpg" },
  { word: "Carrom",             category: "Sports",  image: "images/carrom.jpg" },
  { word: "Ludo",               category: "Sports",  image: "images/ludo.jpg" },
  { word: "Swimming",           category: "Sports",  image: "images/swimming.jpg" },
  { word: "Running",            category: "Sports",  image: "images/running.jpg" },
  { word: "Chess",              category: "Sports",  image: "images/chess.jpg" },
  { word: "Cycling",            category: "Sports",  image: "images/cycling.jpg" },
  { word: "Snakes and Ladders", category: "Sports",  image: "images/snakes-and-ladders.jpg" },
  { word: "Minecraft",          category: "Sports",  image: "images/minecraft.jpg" },
  { word: "Roblox",             category: "Sports",  image: "images/roblox.jpg" },
  { word: "GTA 5",              category: "Sports",  image: "images/gta-5.jpg" },
  { word: "Subway Surfers",     category: "Sports",  image: "images/subway-surfers.jpg" },

  // ── Everyday Objects ─────────────────────────────────────────
  { word: "Camera",         category: "Objects",     image: "images/camera.jpg" },
  { word: "Laptop",         category: "Objects",     image: "images/laptop.jpg" },
  { word: "Guitar",         category: "Objects",     image: "images/guitar.jpg" },
  { word: "Piano",          category: "Objects",     image: "images/piano.jpg" },
  { word: "Candle",         category: "Objects",     image: "images/candle.jpg" },
  { word: "Umbrella",       category: "Objects",     image: "images/umbrella.jpg" },
  { word: "Diamond",        category: "Objects",     image: "images/diamond.jpg" },
  { word: "Scissors",       category: "Objects",     image: "images/scissors.jpg" },
  { word: "Kite",           category: "Objects",     image: "images/kite.jpg" },
  { word: "Trophy",         category: "Objects",     image: "images/trophy.jpg" },
  { word: "Mobile Phone",   category: "Objects",     image: "images/mobile-phone.jpg" },
  { word: "Television",     category: "Objects",     image: "images/television.jpg" },
  { word: "Shoes",          category: "Objects",     image: "images/shoes.jpg" },
  { word: "Mirror",         category: "Objects",     image: "images/mirror.jpg" },
  { word: "Newspaper",      category: "Objects",     image: "images/newspaper.jpg" },
  { word: "Bucket",         category: "Objects",     image: "images/bucket.jpg" },
  { word: "Fan",            category: "Objects",     image: "images/fan.jpg" },
  { word: "Bulb",           category: "Objects",     image: "images/bulb.jpg" },
  { word: "Coin",           category: "Objects",     image: "images/coin.jpg" },
  { word: "Soap",           category: "Objects",     image: "images/soap.jpg" },
  { word: "Torch",          category: "Objects",     image: "images/torch.jpg" },
  { word: "Toothbrush",     category: "Objects",     image: "images/toothbrush.jpg" },
  { word: "Spoon",          category: "Objects",     image: "images/spoon.jpg" },
  { word: "Chair",          category: "Objects",     image: "images/chair.jpg" },

  // ── School Stationery ────────────────────────────────────────
  { word: "Pencil",         category: "Stationery",  image: "images/pencil.jpg" },
  { word: "Pen",            category: "Stationery",  image: "images/pen.jpg" },
  { word: "Eraser",         category: "Stationery",  image: "images/eraser.jpg" },
  { word: "Sharpener",      category: "Stationery",  image: "images/sharpener.jpg" },
  { word: "Scale",          category: "Stationery",  image: "images/scale.jpg" },
  { word: "Notebook",       category: "Stationery",  image: "images/notebook.jpg" },
  { word: "Crayon",         category: "Stationery",  image: "images/crayon.jpg" },
  { word: "Glue",           category: "Stationery",  image: "images/glue.jpg" },
  { word: "Water Bottle",   category: "Stationery",  image: "images/water-bottle.jpg" },

  // ── Professions ──────────────────────────────────────────────
  { word: "Doctor",         category: "Professions", image: "images/doctor.jpg" },
  { word: "Police",         category: "Professions", image: "images/police.jpg" },
  { word: "Teacher",        category: "Professions", image: "images/teacher.jpg" },
  { word: "Soldier",        category: "Professions", image: "images/soldier.jpg" },
  { word: "Astronaut",      category: "Professions", image: "images/astronaut.jpg" },
  { word: "Farmer",         category: "Professions", image: "images/farmer.jpg" },
  { word: "Barber",         category: "Professions", image: "images/barber.jpg" },
  { word: "Cook",           category: "Professions", image: "images/cook.jpg" },

  // ── Body Parts ───────────────────────────────────────────────
  { word: "Eyes",           category: "Body Parts",  image: "images/eyes.jpg" },
  { word: "Ears",           category: "Body Parts",  image: "images/ears.jpg" },
  { word: "Nose",           category: "Body Parts",  image: "images/nose.jpg" },
  { word: "Mouth",          category: "Body Parts",  image: "images/mouth.jpg" },
  { word: "Hands",          category: "Body Parts",  image: "images/hands.jpg" },
  { word: "Legs",           category: "Body Parts",  image: "images/legs.jpg" },
  { word: "Teeth",          category: "Body Parts",  image: "images/teeth.jpg" },
  { word: "Tongue",         category: "Body Parts",  image: "images/tongue.jpg" },
  { word: "Hair",           category: "Body Parts",  image: "images/hair.jpg" },
  { word: "Finger",         category: "Body Parts",  image: "images/finger.jpg" },

  // ── Random ───────────────────────────────────────────────────
  { word: "Dragon",         category: "Random",      image: "images/dragon.jpg" },
  { word: "Robot",          category: "Random",      image: "images/robot.jpg" },
  { word: "Drone",          category: "Random",      image: "images/drone.jpg" },
  { word: "Calculator",     category: "Random",      image: "images/calculator.jpg" },
  { word: "Watch",          category: "Random",      image: "images/watch.jpg" },
  { word: "Teddy",          category: "Random",      image: "images/teddy.jpg" },
  { word: "Mask",           category: "Random",      image: "images/mask.jpg" },
  { word: "Helmet",         category: "Random",      image: "images/helmet.jpg" },
  { word: "Ring",           category: "Random",      image: "images/ring.jpg" },
  { word: "Bag",            category: "Random",      image: "images/bag.jpg" },
  { word: "Key",            category: "Random",      image: "images/key.jpg" },
  { word: "Comb",           category: "Random",      image: "images/comb.jpg" },
  { word: "Balloon",        category: "Random",      image: "images/balloon.jpg" },
  { word: "Bell",           category: "Random",      image: "images/bell.jpg" },
  { word: "Charger",        category: "Random",      image: "images/charger.jpg" },
  { word: "Ladder",         category: "Random",      image: "images/ladder.jpg" },

];

console.log(`📚 Words loaded: ${WORDS.length}`);
